name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork repository
        uses: actions/checkout@v3

      - name: Configure Git user
        run: |
          git config --global user.name "VictoKu1"
          git config --global user.email "victoku1.info@gmail.com"
          
      - name: Add upstream remote and sync
        run: |
          git remote add upstream https://github.com/deepseek-ai/Janus.git
          git fetch upstream
          git checkout main
          git merge upstream/main --allow-unrelated-histories
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          














